"""create tables: tag, task_tag

Revision ID: 2e7b6c1a1a92
Revises: 00481b4aee6d
Create Date: 2021-09-07 19:10:32.907859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7b6c1a1a92'
down_revision = '00481b4aee6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag'))
    )
    op.create_table('task_tag',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_task_tag_tag_id_tag')),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_tag_task_id_task'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
