"""create table: task_clock

Revision ID: 6a24122a94bf
Revises: 2e7b6c1a1a92
Create Date: 2021-09-07 23:19:32.695845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a24122a94bf'
down_revision = '2e7b6c1a1a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_clock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('stop_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_clock_task_id_task')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_clock'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_clock')
    # ### end Alembic commands ###
