"""update table: daily_entry - date, created_date

Revision ID: 6b03990a6cf0
Revises: 6a24122a94bf
Create Date: 2021-09-13 14:11:38.958793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b03990a6cf0'
down_revision = '6a24122a94bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_entry', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
